import type { PassName, SchemaVersion } from "./types.js";

function buildTraceActions(version: SchemaVersion): string {
  return version === "v0.5"
    ? "anchor_add, anchor_relax, fork, suspend, obstruct, revive, resolve, retire, project, contract_shift, negotiate, audit_rewrite, reframe"
    : "anchor_add, anchor_relax, fork, suspend, obstruct, revive, resolve, retire, project, contract_shift, negotiate, audit_rewrite";
}

function buildStateUpdaterSupplement(version: SchemaVersion): string {
  const topLevelKeys =
    version === "v0.5"
      ? "version, turn, rationale, contract_patch, add_anchors, update_anchor_status, update_anchor_exposure, add_sections, update_sections, add_interpretation_openings, update_interpretation_openings, add_rejected_variants, add_voids, resolve_voids, add_obstructions, clear_obstructions, add_negotiations, update_negotiations, traces"
      : "version, turn, rationale, contract_patch, add_anchors, update_anchor_status, add_sections, update_sections, add_voids, resolve_voids, add_obstructions, clear_obstructions, add_negotiations, update_negotiations, traces";
  const v05Lines =
    version === "v0.5"
      ? [
          "- update_anchor_exposure items must use exactly these keys:",
          "  id, exposure_policy, reason",
          "- exposure_policy must be one of exactly:",
          "  latent, expose_if_touched, always_expose",
          "- add_interpretation_openings items must use exactly these keys:",
          "  id, label, reading, changes_if_selected, clarification_prompt, collapsible_with_one_clarification, status, competes_with, related_sections",
          "- interpretation_openings[*].status must be one of exactly:",
          "  open, selected, collapsed, rejected",
          "- add_rejected_variants items must use exactly these keys:",
          "  id, kind, label, summary, derived_from, rejected_by, reason, superseded_by, turn",
          "- rejected_variants[*].kind must be one of exactly:",
          "  interpretation_frame, section_variant, frontier, claim_strategy",
          "- rejected_variants[*].rejected_by must be one of exactly:",
          "  user, system, audit, inferred",
          "- If a question has materially different plausible readings, prefer add_interpretation_openings over forcing one section too early.",
          "- Use add_interpretation_openings for interpretive ambiguity, not for missing facts.",
          "- Use add_voids for unknown facts/referents; use interpretation_openings for multiple plausible readings of the same visible user turn.",
          "- If choosing one reading would materially change examples, order, genre, tone, or scope, keep more than one interpretation_opening live.",
          "- If one live reading is 'define first' and another is 'give examples first', preserve both unless the user clearly selected one.",
          "- If one live reading is culturally or genre specific and another is generic, do not silently naturalize the specific frame.",
          "- If the user explicitly rejects a prior framing, preserve it in add_rejected_variants instead of silently overwriting the section history.",
          "- When a prior framing is rejected but still relevant as dialogue residue, keep it in add_rejected_variants and mark the new live reading separately.",
          "- If two or more live interpretation_openings would lead to materially different answers, prefer add_obstructions or add_negotiations over silently narrowing.",
          "- Use reframe only when a prior framing is explicitly corrected or replaced.",
          "- Use domain_mode to mark what kind of world the section is operating inside: factual for truth-tracking, hypothetical for what-if reasoning, fictional for invented/story space, symbolic for metaphor/allegory-heavy reading.",
          "- If domain_mode is hypothetical, fictional, or symbolic, do not create a void just because the referent is invented or underdescribed.",
          "- In non-factual domain_mode, use add_voids only for real blocking constraints that would materially change the answer shape or safety boundary.",
        ]
      : [];

  return [
    "OUTPUT_SHAPE_REMINDERS:",
    "- Return exactly one JSON object with exactly these top-level keys:",
    `  ${topLevelKeys}`,
    "- rationale must be a plain string, not an object.",
    "- Every update_* field here is an array, even when empty.",
    "- Never use top-level keys like trace, anchor, void, section, contract, negotiation, revive, retire, or suspend.",
    "- add_sections items must use exactly these keys:",
    version === "v0.5"
      ? "  id, label, gist, warrant, domain_mode, status, parents, revive_when, projection_signature, branch_cost, variants"
      : "  id, label, gist, warrant, status, parents, revive_when, projection_signature, branch_cost, variants",
    "- add_sections[*].warrant must be one of exactly:",
    "  local_inference, user_asserted, source_observed, externally_verified",
    ...(version === "v0.5"
      ? [
          "- add_sections[*].domain_mode must be one of exactly:",
          "  factual, hypothetical, fictional, symbolic",
        ]
      : []),
    "- add_sections[*].status must be one of exactly:",
    "  active, latent, frozen, retired",
    "- add_voids items must use exactly these keys:",
    "  id, question, effect, effect_scope, coupled_with, coupling_mode, resolution_priority, unresolved_blocks, exposure_required_if_touched, status, resolution_requires",
    "- add_voids[*].effect must be one of exactly:",
    "  changes_entire_content, changes_content_selection, changes_risk_boundary, changes_tone, changes_ordering, changes_evaluation_boundary",
    "- add_voids[*].effect_scope must be one of exactly:",
    "  local, global",
    "- add_voids[*].coupling_mode must be one of exactly:",
    "  none, joint, gated_by, parent_of",
    "- add_voids[*].status must be one of exactly:",
    "  open, parked, resolved",
    "- add_voids[*].resolution_priority must be one of exactly:",
    "  low, medium, high, critical",
    "- add_obstructions items must use exactly these keys:",
    "  id, between, type, note, bridge_risk, exposure_operator, clearance_modes, status",
    "- add_obstructions[*].type must be one of exactly:",
    "  semantic_split, goal_tension, evidence_gap, value_conflict, time_conflict, anchor_conflict",
    "- add_obstructions[*].bridge_risk must be one of exactly:",
    "  low, medium, high",
    "- add_obstructions[*].exposure_operator must be one of exactly:",
    "  premise_disclosure, scope_boundary, withheld_alternative, tradeoff_note, branched_projection",
    "- add_obstructions[*].status must be one of exactly:",
    "  active, cleared",
    "- add_negotiations items must use exactly these keys:",
    "  id, anchors, unsat_core, frontiers, selected, reason, alternatives_preserved, status",
    "- add_negotiations[*].status must be one of exactly:",
    "  active, settled",
    "- add_negotiations[*].frontiers items must use exactly these keys:",
    "  id, satisfies, relaxes, projection_delta, exposure_cost",
    "- add_negotiations[*].frontiers[*].exposure_cost must be one of exactly:",
    "  low, medium, high",
    "- traces items must use exactly these keys:",
    "  id, action, targets, cause, turn",
    "- Valid trace actions are exactly:",
    `  ${buildTraceActions(version)}`,
    "- Do not emit anchor_add for an already-existing active anchor unless that anchor is newly created in add_anchors.",
    "- Do not invent trace actions like void or void_add. If add_voids is non-empty and no canonical trace action fits, omit that trace.",
    ...v05Lines,
    "",
    "MINIMAL_VALID_TOP_LEVEL_EXAMPLE:",
    "{",
    `  "version": "${version}",`,
    '  "turn": 1,',
    '  "rationale": "User turn does not require any structural change.",',
    '  "contract_patch": {},',
    '  "add_anchors": [],',
    '  "update_anchor_status": [],',
    ...(version === "v0.5" ? ['  "update_anchor_exposure": [],'] : []),
    '  "add_sections": [],',
    '  "update_sections": [],',
    ...(version === "v0.5"
      ? [
          '  "add_interpretation_openings": [],',
          '  "update_interpretation_openings": [],',
          '  "add_rejected_variants": [],',
        ]
      : []),
    '  "add_voids": [],',
    '  "resolve_voids": [],',
    '  "add_obstructions": [],',
    '  "clear_obstructions": [],',
    '  "add_negotiations": [],',
    '  "update_negotiations": [],',
    '  "traces": []',
    "}",
    "",
    "VALID_add_section_ITEM_EXAMPLE:",
    "{",
    '  "id": "S1",',
    '  "label": "Symbolic interpretations",',
    '  "gist": "Possible interpretations remain distinct pending context.",',
    '  "warrant": "local_inference",',
    ...(version === "v0.5" ? ['  "domain_mode": "symbolic",'] : []),
    '  "status": "latent",',
    '  "parents": [],',
    '  "revive_when": [],',
    '  "projection_signature": {',
    '    "allowed_claim_set": ["descriptive"],',
    '    "mandatory_exposures": [],',
    '    "clarification_needs": [],',
    '    "anchor_touch": ["A1"],',
    '    "obstruction_touch": []',
    "  },",
    '  "branch_cost": {',
    '    "cognitive_load": 2,',
    '    "projection_block_risk": 2,',
    '    "obstruction_yield": 3,',
    '    "revive_likelihood": "medium"',
    "  },",
    '  "variants": []',
    "}",
    ...(version === "v0.5"
      ? [
          "",
          "VALID_add_interpretation_opening_ITEM_EXAMPLE:",
          "{",
          '  "id": "I1",',
          '  "label": "definition_vs_examples",',
          '  "reading": "The question can be read as asking for a definition first or for examples first.",',
          '  "changes_if_selected": "It changes whether the answer frames the space before instantiating it.",',
          '  "clarification_prompt": "Should the answer define the space first, or jump straight to examples?",',
          '  "collapsible_with_one_clarification": true,',
          '  "status": "open",',
          '  "competes_with": [],',
          '  "related_sections": []',
          "}",
          "",
          "VALID_add_rejected_variant_ITEM_EXAMPLE:",
          "{",
          '  "id": "R1",',
          '  "kind": "section_variant",',
          '  "label": "narrow confirmation-reading",',
          '  "summary": "A prior answer narrowed the question too quickly to one conversational frame.",',
          '  "derived_from": ["S1"],',
          '  "rejected_by": "user",',
          '  "reason": "The user rejected this framing as too narrow.",',
          '  "superseded_by": ["I1"],',
          '  "turn": 1',
          "}",
        ]
      : []),
    "",
    "VALID_add_void_ITEM_EXAMPLE:",
    "{",
    '  "id": "V1",',
    '  "question": "Which tradition or artwork does the three-fish image come from?",',
    '  "effect": "changes_content_selection",',
    '  "effect_scope": "global",',
    '  "coupled_with": [],',
    '  "coupling_mode": "none",',
    '  "resolution_priority": "high",',
    '  "unresolved_blocks": ["content claims"],',
    '  "exposure_required_if_touched": true,',
    '  "status": "open",',
    '  "resolution_requires": []',
    "}",
    "",
    "VALID_add_obstruction_ITEM_EXAMPLE:",
    "{",
    '  "id": "O1",',
    '  "between": ["I1", "I2"],',
    '  "type": "semantic_split",',
    '  "note": "Two live readings would produce materially different answer shapes.",',
    '  "bridge_risk": "medium",',
    '  "exposure_operator": "withheld_alternative",',
    '  "clearance_modes": ["scope_boundary", "branched_projection"],',
    '  "status": "active"',
    "}",
    "",
    "VALID_add_negotiation_ITEM_EXAMPLE:",
    "{",
    '  "id": "N1",',
    '  "anchors": ["A1"],',
    '  "unsat_core": ["I1", "I2"],',
    '  "frontiers": [',
    "    {",
    '      "id": "F1",',
    '      "satisfies": ["define-first"],',
    '      "relaxes": [],',
    '      "projection_delta": "Frame the answer before giving examples.",',
    '      "exposure_cost": "low"',
    "    },",
    "    {",
    '      "id": "F2",',
    '      "satisfies": ["examples-first"],',
    '      "relaxes": [],',
    '      "projection_delta": "Jump directly to examples without prior framing.",',
    '      "exposure_cost": "medium"',
    "    }",
    "  ],",
    '  "selected": "",',
    '  "reason": "",',
    '  "alternatives_preserved": [],',
    '  "status": "active"',
    "}",
    "",
    "VALID_trace_ITEM_EXAMPLE:",
    "{",
    '  "id": "T1",',
    `  "action": "${version === "v0.5" ? "reframe" : "fork"}",`,
    `  "targets": [${version === "v0.5" ? '"S1", "R1"' : '"S1"'}],`,
    `  "cause": "${version === "v0.5"
      ? "The user corrected a prior narrowing and the frame was reopened."
      : "A new section was created because downstream claim permissions differ."}",`,
    '  "turn": 1',
    "}",
  ].join("\n").trim();
}

function buildNegotiatorSupplement(version: SchemaVersion): string {
  return [
    "OUTPUT_SHAPE_REMINDERS:",
    "- Return exactly one JSON object with exactly these top-level keys:",
    "  version, turn, projection_style_recommendation, global_reason, decisions, traces",
    "- decisions must always be an array, even when empty.",
    "- If there are no active negotiations in CURRENT_STATE_JSON, set decisions to [].",
    "- Do not return wrapper objects like result, frontiers, ranking, or notes at the top level.",
    "- Put explanatory prose in global_reason or decision.reason, not in traces.",
    "- If no canonical trace action fits, set traces to [].",
    "- If decisions is [], traces should also be [].",
    ...(version === "v0.5"
      ? [
          "- If CURRENT_STATE_JSON has multiple live interpretation_openings, do not default to single unless the state already licenses one reading as selected/collapsed.",
          "- If one clarification could collapse the live readings, projection_style_recommendation should usually be clarify.",
          "- If several readings remain materially valuable to preserve, projection_style_recommendation should usually be branched.",
          "- If content claims would prematurely naturalize one live reading, projection_style_recommendation may need to be meta even when there is no formal negotiation object yet.",
        ]
      : []),
    "- projection_style_recommendation must be one of exactly:",
    "  auto, single, branched, meta, clarify",
    "- decisions items must use exactly these keys:",
    "  negotiation_id, selected_frontier, reason, tradeoff_note, alternatives_preserved, relaxed_anchors",
    "- traces items must use exactly these keys:",
    "  id, action, targets, cause, turn",
    "- Valid trace actions are exactly:",
    `  ${buildTraceActions(version)}`,
    "",
    "MINIMAL_VALID_TOP_LEVEL_EXAMPLE:",
    "{",
    `  "version": "${version}",`,
    '  "turn": 1,',
    '  "projection_style_recommendation": "single",',
    '  "global_reason": "No active negotiation requires a frontier choice.",',
    '  "decisions": [],',
    '  "traces": []',
    "}",
    "",
    "VALID_decision_ITEM_EXAMPLE:",
    "{",
    '  "negotiation_id": "N1",',
    '  "selected_frontier": "F1",',
    '  "reason": "This frontier preserves the active veto while remaining answerable.",',
    '  "tradeoff_note": "Alternative frontiers are preserved but not selected.",',
    '  "alternatives_preserved": ["F2"],',
    '  "relaxed_anchors": []',
    "}",
  ].join("\n").trim();
}

function buildProjectCompilerSupplement(version: SchemaVersion): string {
  const projectionIrKeys =
    version === "v0.5"
      ? "selected_frontiers, frame_commitments, claim_frames, scars, withheld, body_plan"
      : "selected_frontiers, claim_frames, scars, withheld, body_plan";

  return [
    "OUTPUT_SHAPE_REMINDERS:",
    "- Return exactly one JSON object with exactly these top-level keys:",
    "  version, turn, projection_ir, answer",
    "- answer must be a plain string, not an object.",
    "- projection_ir must use exactly these keys:",
    `  ${projectionIrKeys}`,
    ...(version === "v0.5"
      ? [
          "- frame_commitments must be an array, even when empty.",
          "- If CURRENT_STATE_JSON has live interpretation_openings and the answer commits to one framing, include the relevant opening ids in frame_commitments.",
          "- If more than one live interpretation_opening remains open, do not silently naturalize one reading as if it were the only live frame.",
          "- If one opening is definition-first and another is examples-first, either expose the framing choice or stay frame-light before giving examples.",
          "- If one opening is culturally or genre specific and that choice is not yet licensed, do not jump straight to that domain.",
          "- If CURRENT_STATE_JSON includes rejected_variants, do not revive those framings as if they were still live or canonical.",
          "- If the selected section or frame is hypothetical, fictional, or symbolic, speculative claims are allowed when they are clearly framed as generated rather than externally verified.",
          "- In non-factual domains, do not block just because the subject is invented; use claim kind speculative when the answer is imaginatively generated.",
        ]
      : []),
    "- claim_frames items must use exactly these keys:",
    "  id, section, kind, text_intent, warrant, depends_on, licensed_if, drop_if_unexposed",
    "- claim_frames[*].kind must be one of exactly:",
    version === "v0.5"
      ? "  descriptive, causal, comparative, normative, procedural, meta, speculative"
      : "  descriptive, causal, comparative, normative, procedural, meta",
    "- claim_frames[*].warrant must be one of exactly:",
    "  local_inference, user_asserted, source_observed, externally_verified",
    "- scars items must use exactly these keys:",
    "  id, from, leakage_if_hidden, severity, scope, operator, compressible, bundle_key, attached_to",
    "- scars[*].leakage_if_hidden must be one of exactly:",
    "  false_completeness, causal_overreach, audience_misfit, boundary_breach, false_finality, false_consensus",
    "- scars[*].severity must be one of exactly:",
    "  low, medium, high",
    "- scars[*].scope must be one of exactly:",
    "  claim, sentence, block, answer",
    "- scars[*].operator must be one of exactly:",
    "  premise_disclosure, scope_boundary, withheld_alternative, tradeoff_note, branched_projection",
    "- withheld items must use exactly these keys:",
    "  id, item, reason, recover_when, expose_if_material",
    "- body_plan must use exactly these keys:",
    "  intro_scars, claims, close_withheld, tradeoff_notes",
    "- If unsure, prefer:",
    `  ${version === "v0.5" ? "selected_frontiers: [], frame_commitments: [], scars: [], withheld: []" : "selected_frontiers: [], scars: [], withheld: []"}`,
    "- Keep active anchors latent by default.",
    "- Do not mention anchor text or generic causal-safety caveats in the answer unless a specific claim would otherwise mislead the reader.",
    "- Avoid routine endings like \"因果関係には触れない\" when the answer is already safely descriptive.",
    "",
    "MINIMAL_VALID_TOP_LEVEL_EXAMPLE:",
    "{",
    `  "version": "${version}",`,
    '  "turn": 1,',
    '  "projection_ir": {',
    '    "selected_frontiers": [],',
    ...(version === "v0.5" ? ['    "frame_commitments": [],'] : []),
    '    "claim_frames": [',
    "      {",
    '        "id": "C1",',
    '        "section": "S1",',
    '        "kind": "meta",',
    '        "text_intent": "State that a safe answer is limited by missing context.",',
    '        "warrant": "local_inference",',
    '        "depends_on": [],',
    '        "licensed_if": [],',
    '        "drop_if_unexposed": false',
    "      }",
    "    ],",
    '    "scars": [],',
    '    "withheld": [],',
    '    "body_plan": {',
    '      "intro_scars": [],',
    '      "claims": ["C1"],',
    '      "close_withheld": [],',
    '      "tradeoff_notes": []',
    "    }",
    "  },",
    '  "answer": "Context is limited, so the answer stays within the safely licensed range."',
    "}",
  ].join("\n").trim();
}

function buildAuditorSupplement(version: SchemaVersion): string {
  const categories =
    version === "v0.5"
      ? "provenance, bridge, implicature, scope_coverage, negotiation_fidelity, unsupported_claim, scar_underexposure, scar_overexposure, frame_narrowing"
      : "provenance, bridge, implicature, scope_coverage, negotiation_fidelity, unsupported_claim, scar_underexposure, scar_overexposure";

  return [
    "OUTPUT_SHAPE_REMINDERS:",
    "- Return exactly one JSON object with exactly these top-level keys:",
    "  version, turn, verdict, summary, required_actions, projection_style_recommendation, findings",
    "- Do not return wrapper objects like checks or revision_suggestions.",
    "- summary must be a plain string.",
    "- required_actions must be an array, even when empty.",
    "- findings must be an array, even when empty.",
    "- If verdict is pass and there are no open issues, prefer required_actions: [] and findings: [].",
    "- verdict must be exactly one of:",
    "  pass, revise, block",
    "- projection_style_recommendation must be exactly one of:",
    "  auto, single, branched, meta, clarify",
    "- findings items must use exactly these keys:",
    "  id, category, severity, target_ids, description, fix, status",
    "- findings[*].category must be one of exactly:",
    `  ${categories}`,
    "- findings[*].severity must be one of exactly:",
    "  low, medium, high",
    "- findings[*].fix must be one of exactly:",
    "  add_scar, drop_claim, shrink_claim, rebundle_scars, switch_projection_style, add_tradeoff_note, rewrite",
    "- findings[*].status must be one of exactly:",
    "  open, resolved",
    "- Optional fields, only when needed for a revision:",
    "  revised_answer, revised_projection_ir",
    "- If a claim with warrant local_inference is phrased as settled fact too strongly, use verdict revise and add an unsupported_claim finding.",
    "- If the answer surfaces a latent anchor or generic caveat that is not materially needed, use verdict revise and add a scar_overexposure finding.",
    ...(version === "v0.5"
      ? [
          "- If CURRENT_STATE_JSON has live interpretation_openings and PROJECTION_OUTPUT_JSON commits to one frame without surfacing that narrowing, use verdict revise and add a frame_narrowing finding.",
          "- Also use frame_narrowing when the answer jumps to examples even though a live reading would require framing or definition first.",
          "- Also use frame_narrowing when the answer silently chooses a culture, genre, or tradition while that framing remains live and unresolved.",
          "- If the answer revives a CURRENT_STATE_JSON rejected_variant as if it were live again, use verdict revise and add a frame_narrowing finding.",
          "- Use target_ids to point at interpretation opening ids or rejected variant ids when they are part of the narrowing problem.",
        ]
      : []),
    "",
    "MINIMAL_VALID_TOP_LEVEL_EXAMPLE:",
    "{",
    `  "version": "${version}",`,
    '  "turn": 1,',
    '  "verdict": "pass",',
    '  "summary": "The answer stays within the licensed scope.",',
    '  "required_actions": [],',
    '  "projection_style_recommendation": "single",',
    '  "findings": []',
    "}",
    "",
    "VALID_finding_ITEM_EXAMPLE:",
    "{",
    '  "id": "F1",',
    `  "category": "${version === "v0.5" ? "frame_narrowing" : "scope_coverage"}",`,
    '  "severity": "medium",',
    `  "target_ids": [${version === "v0.5" ? '"I1"' : '"SC1"'}],`,
    `  "description": "${version === "v0.5"
      ? "Several live readings remain, but the answer implicitly committed to one without licensing the narrowing."
      : "A local dependency needs a more local scar."}",`,
    `  "fix": "${version === "v0.5" ? "rewrite" : "add_scar"}",`,
    '  "status": "open"',
    "}",
  ].join("\n").trim();
}

export function appendPromptSupplement(
  pass: PassName,
  schemaVersion: SchemaVersion,
  userPrompt: string,
): string {
  const supplement = (() => {
    switch (pass) {
      case "state_updater":
        return buildStateUpdaterSupplement(schemaVersion);
      case "negotiator":
        return buildNegotiatorSupplement(schemaVersion);
      case "project_compiler":
        return buildProjectCompilerSupplement(schemaVersion);
      case "auditor":
        return buildAuditorSupplement(schemaVersion);
      default:
        return "";
    }
  })();

  return supplement ? `${userPrompt}\n\n${supplement}` : userPrompt;
}
